# ===== Global =====
persistence true
log_type all

# ===== Listener MQTT TCP =====
listener 1883
protocol mqtt
listener_allow_anonymous true

# ===== Listener WebSocket =====
listener 8082
protocol websockets
listener_allow_anonymous true
http_dir .